// scripts/config/talent-book-mapping.ts
// Bảng mapping nhân vật -> sách talent (cập nhật thủ công từ wiki)
// Đây là nơi duy nhất bạn cần sửa khi có nhân vật mới.

export const TALENT_BOOK_SERIES_BY_CHARACTER: Record<string, string> = {
  // Mondstadt
  amber: "freedom",
  barbara: "freedom",
  sucrose: "freedom",
  klee: "freedom",
  diona: "freedom",
  tartaglia: "freedom",
  aloy: "freedom",
  varka: "freedom",
  bennett: "resistance",
  diluc: "resistance",
  eula: "resistance",
  jean: "resistance",
  mona: "resistance",
  noelle: "resistance",
  razor: "resistance",
  albedo: "ballad",
  dahlia: "ballad",
  durin: "ballad",
  fischl: "ballad",
  kaeya: "ballad",
  lisa: "ballad",
  mika: "ballad",
  rosaria: "ballad",
  venti: "ballad",

  // Liyue
  gaming: "prosperity",
  keqing: "prosperity",
  ningguang: "prosperity",
  qiqi: "prosperity",
  shenhe: "prosperity",
  xiao: "prosperity",
  yelan: "prosperity",
  chongyun: "diligence",
  ganyu: "diligence",
  hu_tao: "diligence",
  kaedehara_kazuha: "diligence",
  lan_yan: "diligence",
  xiangling: "diligence",
  yaoyao: "diligence",
  yun_jin: "diligence",
  beidou: "gold",
  xingqiu: "gold",
  zhongli: "gold",
  xinyan: "gold",
  yanfei: "gold",
  baizhu: "gold",
  xianyun: "gold",

  // Inazuma
  kirara: "transience",
  sangonomiya_kokomi: "transience",
  shikanoin_heizou: "transience",
  thoma: "transience",
  yoimiya: "transience",
  yumemizuki_mizuki: "transience",
  arataki_itto: "elegance",
  kamisato_ayaka: "elegance",
  kamisato_ayato: "elegance",
  kujou_sara: "elegance",
  kuki_shinobu: "elegance",
  chiori: "light",
  gorou: "light",
  raiden_shogun: "light",
  sayu: "light",
  yae_miko: "light",

  // Sumeru
  candace: "admonition",
  cyno: "admonition",
  faruzan: "admonition",
  tighnari: "admonition",
  alhaitham: "ingenuity",
  dori: "ingenuity",
  kaveh: "ingenuity",
  layla: "ingenuity",
  nahida: "ingenuity",
  collei: "praxis",
  dehya: "praxis",
  nilou: "praxis",
  sethos: "praxis",
  wanderer: "praxis",

  // Fontaine
  lyney: "equity",
  navia: "equity",
  neuvillette: "equity",
  sigewinne: "equity",
  charlotte: "justice",
  clorinde: "justice",
  escoffier: "justice",
  freminet: "justice",
  furina: "justice",
  wriothesley: "order",
  chevreuse: "order",
  emilie: "order",
  arlecchino: "order",
  lynette: "order",

  // Natlan
  skirk: "contention",
  mualani: "contention",
  mavuika: "contention",
  kinich: "kindling",
  xilonen: "kindling",
  ororon: "kindling",
  chasca: "conflict",
  citlali: "conflict",
  iansan: "conflict",
  kachina: "conflict",
  ifa: "conflict",
  ineffa: "conflict",
  varesa: "conflict",

  // Nod-Krai
  columbina: "moonlight",
  lauma: "moonlight",
  nefer: "elysium",
  sandrone: "vagrancy",
};

// Traveler: mỗi nguyên tố dùng sách của vùng tương ứng
export const TRAVELER_ELEMENT_TO_BOOK: Record<string, string> = {
  Anemo: "freedom",
  Geo: "prosperity",
  Electro: "elegance",
  Dendro: "praxis",
  Hydro: "equity",
  Pyro: "contention",
  Cryo: "ballad",
};